-- AUTO-GENERATED FILE. Do not edit directly.
-- Generated by tools/convert_ldtk_plum_mirror_to_lua.ps1 from ldtk/ink_plum_mirror.ldtk.

LDTK_PLUM_MIRROR = {
    source = "ldtk/ink_plum_mirror.ldtk",
    identifier = "UrhoX_Level_12_Plum_Mirror",
    width = 4480,
    height = 1584,
    materials = {
        paper = { 246, 237, 225 },
        paper2 = { 220, 207, 190 },
        ink = { 42, 30, 24 },
        wash = { 114, 82, 69 },
        accent = { 142, 35, 42 },
        bloom = { 195, 18, 18 },
        water = { 204, 165, 68 },
    },
    physics = { radius = 11, gravity = 0.46, jumpForce = -16.5, dashSpeed = 21, friction = 0.84 },
    start = { x = 639, y = 922, facing = "right", },
    branches = {
        { id = "main_trunk", x1 = 224, y1 = 950.4, x2 = 1881.6, y2 = 1045.44, startR = 46, endR = 32, curveX = 80, curveY = 50, pointsNum = 60, jitter = 0.1 },
        { id = "hanging_branch", x1 = 1881.6, y1 = 1045.44, x2 = 2777.6, y2 = 1172.16, startR = 32, endR = 20, curveX = 60, curveY = 30, pointsNum = 50, jitter = 0.1 },
        { id = "right_crescent", x1 = 1881.6, y1 = 1045.44, x2 = 3225.6, y2 = 792, startR = 30, endR = 16, curveX = 100, curveY = -80, pointsNum = 60, jitter = 0.1 },
        { id = "upright_young_shoot", x1 = 1568, y1 = 950.4, x2 = 2508.8, y2 = 380.16, startR = 18, endR = 8, curveX = 30, curveY = -100, pointsNum = 70, jitter = 0.1 },
        { id = "poetry_col_1", x1 = 3673.6, y1 = 443.52, x2 = 3673.6, y2 = 982.08, startR = 4, endR = 4, curveX = 0, curveY = 0, pointsNum = 20, jitter = 0 },
        { id = "poetry_col_2", x1 = 3852.8, y1 = 443.52, x2 = 3852.8, y2 = 982.08, startR = 4, endR = 4, curveX = 0, curveY = 0, pointsNum = 20, jitter = 0 },
        { id = "poetry_col_3", x1 = 4032, y1 = 443.52, x2 = 4032, y2 = 982.08, startR = 4, endR = 4, curveX = 0, curveY = 0, pointsNum = 20, jitter = 0 },
        { id = "poetry_col_4", x1 = 4211.2, y1 = 443.52, x2 = 4211.2, y2 = 982.08, startR = 4, endR = 4, curveX = 0, curveY = 0, pointsNum = 20, jitter = 0 },
    },
    targets = {
        { branchId = "main_trunk", progress = 0.5, radius = 38 },
        { branchId = "hanging_branch", progress = 0.4, radius = 38 },
        { branchId = "hanging_branch", progress = 0.9, radius = 38 },
        { branchId = "upright_young_shoot", progress = 0.4, radius = 38 },
        { branchId = "upright_young_shoot", progress = 0.9, radius = 38 },
        { branchId = "right_crescent", progress = 0.35, radius = 38 },
        { branchId = "right_crescent", progress = 0.8, radius = 38 },
        { branchId = "poetry_col_1", progress = 0.6, radius = 38 },
    },
}
